-- Rollback migration 0000_mature_betty_brant.sql
-- Auto-generated by scripts/generate-rollback.ts
-- Review and modify as needed before running

DROP TABLE IF EXISTS "registrations" CASCADE;
DROP TABLE IF EXISTS "organizations" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "events" CASCADE;
DROP TABLE IF EXISTS "user_badges" CASCADE;
DROP TABLE IF EXISTS "badges" CASCADE;
DROP TABLE IF EXISTS "event_analytics" CASCADE;
