-- Rollback migration 0001_slimy_praxagora.sql
-- Auto-generated by scripts/generate-rollback.ts
-- Review and modify as needed before running

ALTER TABLE "events" DROP COLUMN IF EXISTS "venue_image_url";
