-- Rollback migration 0002_lumpy_roulette.sql
-- Auto-generated by scripts/generate-rollback.ts
-- Review and modify as needed before running

ALTER TABLE "events" DROP COLUMN IF EXISTS "longitude";
ALTER TABLE "events" DROP COLUMN IF EXISTS "latitude";
