-- Rollback migration 0003_milky_junta.sql
-- Auto-generated by scripts/generate-rollback.ts
-- Review and modify as needed before running

ALTER TABLE "events" DROP COLUMN IF EXISTS "location_detail";
