-- Rollback migration 0004_powerful_sheva_callister.sql
-- Auto-generated by scripts/generate-rollback.ts
-- Review and modify as needed before running

ALTER TABLE "users" DROP COLUMN IF EXISTS "interests";
