services:
  app:
    build:
      context: .
      platforms:
        - linux/amd64
    container_name: app
    environment:
      GOMODCACHE: /go/src/app/.modcache
      GOCACHE: /go/src/app/.cache
    env_file:
      - .env.dev
    volumes:
      - "./:/go/src/app"
    ports:
      - "8080:8080"
  #   depends_on:
  #     - mongo

  # mongo:
  #   image: mongo:latest
  #   container_name: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MONGO_INITDB_DATABASE: ${DB_NAME}
  #   env_file:
  #     - .env.dev
  #   volumes:
  #     - "./.mongo-data:/data/lib"
  #   ports:
  #     - "27017:27017"
